"""Flask application: Inventory & Order Management (web version).

Routes:
  /login, /logout           — authentication
  /lang/<lang>              — switch language (EN/ZH)
  /                         — redirect to inventory
  /inventory                — product list (Stage 2)
  /inventory/new, /edit/<id>, /<id>, /delete/<id>, /image/<id>
  /orders, /orders/new, /orders/<id>, ship/unship/delete
  /stats
  /api/timeseries           — JSON for the chart

CLI (run with `flask <command>`):
  flask init-db              — create all tables
  flask create-user <user> <password> [--display "Name"]
"""

from __future__ import annotations

import click
from datetime import date, timedelta

from flask import (
    Flask, render_template, redirect, url_for, request, session,
    Response, flash, jsonify,
)

import db
import repository
from auth import (
    User, admin_required, change_password, current_user, delete_user,
    list_users, login_required, login_user, logout_current_user,
    get_user_by_username, verify_password, create_user,
)
from config import Config
import translations


def _to_rgb(img):
    """Convert any PIL image to RGB, compositing transparency onto white."""
    from PIL import Image
    if img.mode in ("RGBA", "LA", "P"):
        background = Image.new("RGB", img.size, (255, 255, 255))
        if img.mode == "P":
            img = img.convert("RGBA")
        background.paste(img, mask=img.split()[-1] if img.mode in ("RGBA", "LA") else None)
        return background
    if img.mode != "RGB":
        img = img.convert("RGB")
    return img


def _iso(value) -> str:
    """Normalise a date/datetime/str to an ISO 'YYYY-MM-DD' string."""
    if value is None:
        return ""
    if hasattr(value, "isoformat"):
        return value.isoformat()[:10]
    return str(value)[:10]


def _fmt(value) -> str:
    """Format a numeric value with 2 decimals, tolerating None."""
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "0.00"


def _optimise_image(data: bytes, max_size: int = 800, quality: int = 82) -> tuple[bytes, str]:
    """Resize and compress an uploaded image before storing it (full version).

    Caps the longest edge at ``max_size`` and re-encodes as JPEG. This is the
    version served for the full-size lightbox viewer. Returns ``(bytes, ext)``.
    """

    import io
    from PIL import Image

    img = _to_rgb(Image.open(io.BytesIO(data)))
    img.thumbnail((max_size, max_size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=quality, optimize=True)
    return buf.getvalue(), ".jpg"


def _make_thumbnail(data: bytes, size: int = 160, quality: int = 70) -> bytes:
    """Build a tiny square thumbnail (~3-5 KB) for use in lists/tables.

    Used by the ``/product/<id>/thumb`` endpoint so lists never download the
    full image. Result is cropped to a square (cover) at ``size`` px.
    """

    import io
    from PIL import Image

    img = _to_rgb(Image.open(io.BytesIO(data)))
    # Center-crop to a square, then shrink — gives a clean cover thumbnail
    # without distorted aspect ratios.
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=quality, optimize=True)
    return buf.getvalue()


# In-memory thumbnail cache: product_id -> bytes. Rebuilt lazily on first
# access after a deploy; cheap because each thumbnail is only ~3-5 KB.
_thumb_cache: dict[int, bytes] = {}


def create_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object(Config)

    # ---- gzip compression ------------------------------------------------
    # Compresses HTML/JSON responses (~3-5x smaller). Implemented as a tiny
    # after_request hook so no extra dependency (Flask-Compress) is needed.
    import gzip
    import io as _io

    @app.after_request
    def _gzip_response(response):
        # Never touch streamed/static responses (send_file uses
        # direct_passthrough=True, where get_data() breaks and would cause
        # a 500). Only compress normal buffered HTML/JSON/CSS/JS responses
        # generated by our own views.
        if getattr(response, "direct_passthrough", False):
            return response
        accept = request.headers.get("Accept-Encoding", "")
        if "gzip" not in accept.lower():
            return response
        ctype = response.content_type or ""
        if not (ctype.startswith("text/") or "json" in ctype
                or "javascript" in ctype or "css" in ctype):
            return response
        try:
            data = response.get_data()
            if len(data) < 512:
                return response
            buf = _io.BytesIO()
            with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=6, mtime=0) as gz:
                gz.write(data)
            response.set_data(buf.getvalue())
            response.headers["Content-Encoding"] = "gzip"
            response.headers["Vary"] = "Accept-Encoding"
            response.headers["Content-Length"] = len(response.get_data())
        except Exception:
            # Compression must never break a response — fall back to plain.
            pass
        return response

    # ---- Template globals / filters ------------------------------------
    @app.context_processor
    def inject_globals():
        return {
            "current_user": current_user(),
            "tr": translations.tr,
            "lang": translations.get_language(),
        }

    # ---- Authentication -------------------------------------------------
    @app.route("/login", methods=["GET", "POST"])
    def login():
        if request.method == "POST":
            username = request.form.get("username", "").strip()
            password = request.form.get("password", "")
            row = get_user_by_username(username)
            if row and verify_password(row["password_hash"], password):
                login_user(User(row["id"], row["username"],
                                row.get("display_name") or "",
                                row.get("is_admin") or False))
                next_url = request.args.get("next") or url_for("inventory")
                return redirect(next_url)
            flash(translations.tr("login.bad"), "danger")
        return render_template("login.html")

    @app.route("/logout")
    def logout():
        logout_current_user()
        flash(translations.tr("login.signed_out"), "info")
        return redirect(url_for("login"))

    @app.route("/lang/<lang>")
    def set_lang(lang):
        translations.set_language(lang)
        return redirect(request.referrer or url_for("inventory"))

    # ---- Product image serving (binary stored in the DB) ---------------
    @app.route("/product/<int:product_id>/image")
    def product_image(product_id: int):
        """Full-size image — used only by the click-to-zoom lightbox."""
        img = repository.get_product_image(product_id)
        if not img:
            return Response(_PLACEHOLDER_PNG, mimetype="image/png")
        return Response(img, mimetype="image/jpeg",
                        headers={"Cache-Control": "public, max-age=86400"})

    @app.route("/product/<int:product_id>/thumb")
    def product_thumb(product_id: int):
        """Tiny square thumbnail (~3-5 KB) for lists and tables.

        Cached in memory per product id. Lists load this instead of the full
        image, so a page with 50 products downloads ~200 KB instead of ~5 MB.
        """
        thumb = _thumb_cache.get(product_id)
        if thumb is None:
            img = repository.get_product_image(product_id)
            if not img:
                return Response(_PLACEHOLDER_PNG, mimetype="image/png")
            try:
                thumb = _make_thumbnail(img)
            except Exception:
                return Response(_PLACEHOLDER_PNG, mimetype="image/png")
            _thumb_cache[product_id] = thumb
        return Response(thumb, mimetype="image/jpeg",
                        headers={"Cache-Control": "public, max-age=86400"})

    # ---- Inventory ------------------------------------------------------
    @app.route("/")
    def index():
        return redirect(url_for("inventory"))

    @app.route("/inventory")
    @login_required
    def inventory():
        search = request.args.get("search", "").strip() or None
        color = request.args.get("color", "").strip() or None
        size = request.args.get("size", "").strip() or None
        stock_filter = request.args.get("stock", "").strip() or None
        products = repository.list_products(
            search=search, color=color, size=size, stock_filter=stock_filter
        )
        return render_template(
            "inventory/list.html",
            products=products,
            colors=repository.list_all_colors(),
            sizes=repository.list_all_sizes(),
            filters={"search": search or "", "color": color or "", "size": size or "",
                     "stock": stock_filter or ""},
        )

    @app.route("/inventory/new", methods=["GET", "POST"])
    @login_required
    def product_new():
        if request.method == "POST":
            return _save_product(None)
        return render_template("inventory/form.html", product=None,
                               variants=[], colors=repository.list_all_colors(),
                               sizes=repository.list_all_sizes())

    @app.route("/inventory/<int:product_id>/edit", methods=["GET", "POST"])
    @login_required
    def product_edit(product_id: int):
        product = repository.get_product(product_id)
        if not product:
            flash("Product not found.", "danger")
            return redirect(url_for("inventory"))
        if request.method == "POST":
            return _save_product(product_id)
        return render_template("inventory/form.html", product=product,
                               variants=repository.list_variants(product_id),
                               colors=repository.list_all_colors(),
                               sizes=repository.list_all_sizes())

    def _save_product(product_id):
        code = request.form.get("code", "").strip()
        name = request.form.get("name", "").strip()
        if not code or not name:
            flash(translations.tr("err.missing"), "danger")
            return redirect(request.url)
        try:
            price = float(request.form.get("base_price", "0") or 0)
        except ValueError:
            flash(translations.tr("err.invalid_price"), "danger")
            return redirect(request.url)

        # Variants: collected from repeated form fields. Each row submits a
        # v_color/v_size select plus optional v_color_new/v_size_new text
        # inputs (revealed when "add new" was chosen). Resolve server-side —
        # never trust the literal "__new__" sentinel to reach the database.
        colors = request.form.getlist("v_color")
        colors_new = request.form.getlist("v_color_new")
        sizes = request.form.getlist("v_size")
        sizes_new = request.form.getlist("v_size_new")

        def _resolve(values, news, i):
            v = values[i].strip() if i < len(values) else ""
            if v == "__new__":
                v = news[i].strip() if i < len(news) else ""
            return v

        variants = []
        for i in range(max(len(colors), len(sizes))):
            c = _resolve(colors, colors_new, i)
            s = _resolve(sizes, sizes_new, i)
            if c or s:
                variants.append((c, s))
        # Deduplicate preserving order.
        seen = set()
        unique = []
        for c, s in variants:
            if (c, s) not in seen:
                seen.add((c, s))
                unique.append((c, s))

        # Optional image upload.
        image_bytes, image_ext, keep = None, None, True
        upload = request.files.get("image")
        remove = request.form.get("remove_image") == "1"
        if upload and upload.filename:
            data = upload.read()
            if data:
                image_bytes, image_ext = _optimise_image(data)
        elif remove:
            keep = False

        if product_id is None:
            new_id = repository.create_product(
                code, name, price, image_bytes, image_ext, unique
            )
            flash(f"Product #{new_id} created.", "success")
        else:
            repository.update_product(
                product_id, code, name, price, image_bytes, image_ext, unique, keep
            )
            # Invalidate the cached thumbnail so the new image shows up.
            _thumb_cache.pop(product_id, None)
            flash("Product updated.", "success")
        return redirect(url_for("inventory"))

    @app.route("/inventory/<int:product_id>")
    @login_required
    def product_detail(product_id: int):
        product = repository.get_product(product_id)
        if not product:
            flash("Product not found.", "danger")
            return redirect(url_for("inventory"))
        variants = repository.list_variants(product_id)
        stock_in = repository.list_stock_in(product_id)
        stock_out = repository.list_stock_out(product_id)
        # Distinct colors / sizes for the dropdown selectors.
        colors = sorted({v["color"] for v in variants})
        sizes = sorted({v["size"] for v in variants})
        # Combined, newest-first movement history for the History tab.
        history = []
        for r in stock_in:
            history.append({
                "type": "IN", "date": _iso(r["date"]),
                "color": r["color"], "size": r["size"],
                "quantity": r["quantity"],
                "info": f"cost {_fmt(r['unit_cost'])}  {r['note']}".strip(),
            })
        for r in stock_out:
            history.append({
                "type": "OUT", "date": _iso(r["date"]),
                "color": r["color"], "size": r["size"],
                "quantity": r["quantity"],
                "info": f"{r['customer_name']}  {r['note']}".strip(),
            })
        history.sort(key=lambda x: (str(x["date"]), x["type"]), reverse=True)
        return render_template(
            "inventory/detail.html",
            product=product,
            stock_total=repository.product_stock_total(product_id),
            variants=variants,
            stock_in=stock_in,
            stock_out=stock_out,
            colors=colors,
            sizes=sizes,
            history=history,
        )

    @app.route("/inventory/<int:product_id>/stock-in", methods=["POST"])
    @login_required
    def stock_in_add(product_id: int):
        try:
            qty = int(request.form.get("quantity", "0"))
            cost = float(request.form.get("unit_cost", "0") or 0)
        except ValueError:
            flash("Invalid quantity or cost.", "danger")
            return redirect(url_for("product_detail", product_id=product_id))
        repository.add_stock_in(
            product_id,
            request.form.get("color", ""),
            request.form.get("size", ""),
            qty, cost,
            request.form.get("date") or date.today().isoformat(),
            request.form.get("note", ""),
        )
        return redirect(url_for("product_detail", product_id=product_id))

    @app.route("/inventory/<int:product_id>/stock-out", methods=["POST"])
    @login_required
    def stock_out_add(product_id: int):
        try:
            qty = int(request.form.get("quantity", "0"))
        except ValueError:
            flash("Invalid quantity.", "danger")
            return redirect(url_for("product_detail", product_id=product_id))
        repository.add_stock_out(
            product_id,
            request.form.get("color", ""),
            request.form.get("size", ""),
            qty,
            request.form.get("date") or date.today().isoformat(),
            request.form.get("customer_name", ""),
            request.form.get("note", ""),
        )
        return redirect(url_for("product_detail", product_id=product_id))

    @app.route("/inventory/<int:product_id>/adjust", methods=["POST"])
    @login_required
    def stock_adjust(product_id: int):
        """Quick stock adjustment for a specific variant (color/size).

        Lives in the Current stock table on the product detail page: each row
        is one variant, and the ± form submits that variant's exact color and
        size so the movement is attributed correctly.

        Positive delta + direction 'in'  -> stock_in (restock)
        Positive delta + direction 'out' -> stock_out (remove)
        """
        try:
            delta = int(request.form.get("delta", "0") or 0)
        except ValueError:
            delta = 0
        direction = request.form.get("direction", "in")
        color = request.form.get("color", "")
        size = request.form.get("size", "")
        if delta == 0:
            return redirect(url_for("product_detail", product_id=product_id))
        today = date.today().isoformat()
        if direction == "out":
            repository.add_stock_out(product_id, color, size, abs(delta), today,
                                     "", "Quick adjust")
        else:
            product = repository.get_product(product_id) or {}
            repository.add_stock_in(product_id, color, size, abs(delta),
                                    float(product.get("base_price") or 0),
                                    today, "Quick adjust")
        return redirect(url_for("product_detail", product_id=product_id))

    @app.route("/inventory/<int:product_id>/delete", methods=["POST"])
    @login_required
    def product_delete(product_id: int):
        try:
            repository.delete_product(product_id)
            _thumb_cache.pop(product_id, None)
            flash("Product deleted.", "success")
        except Exception as exc:
            flash(f"Cannot delete: {exc}", "danger")
        return redirect(url_for("inventory"))

    # ---- Orders (Stage 3 — basic stubs for now) -----------------------
    @app.route("/orders")
    @login_required
    def orders():
        orders = repository.list_orders(
            search=request.args.get("search", "").strip() or None,
            status=request.args.get("status", "").strip() or None,
            date_from=request.args.get("from", "").strip() or None,
            date_to=request.args.get("to", "").strip() or None,
        )
        return render_template("orders/list.html", orders=orders,
                               filters={"search": request.args.get("search", ""),
                                        "status": request.args.get("status", ""),
                                        "from": request.args.get("from", ""),
                                        "to": request.args.get("to", "")})

    @app.route("/orders/new", methods=["GET", "POST"])
    @login_required
    def order_new():
        if request.method == "POST":
            customer = request.form.get("customer_name", "").strip()
            order_date = request.form.get("order_date") or date.today().isoformat()
            product_ids = request.form.getlist("product_id")
            colors = request.form.getlist("color")
            sizes = request.form.getlist("size")
            qtys = request.form.getlist("quantity")
            prices = request.form.getlist("unit_price")
            items = []
            for pid, c, s, q, p in zip(product_ids, colors, sizes, qtys, prices):
                if not pid:
                    continue
                try:
                    items.append({
                        "product_id": int(pid),
                        "color": c, "size": s,
                        "quantity": int(q), "unit_price": float(p),
                    })
                except (ValueError, TypeError):
                    continue
            if not customer or not items:
                flash("Customer and at least one line item are required.", "danger")
                return redirect(url_for("order_new"))
            oid = repository.create_order(customer, order_date, items)
            flash(translations.tr("info.saved_msg", order_id=oid), "success")
            return redirect(url_for("orders"))
        products = repository.list_products()
        variants_by_product = {
            p["id"]: repository.list_variants(p["id"]) for p in products
        }
        return render_template("orders/form.html", order=None,
                               products=products,
                               variants_by_product=variants_by_product,
                               today=date.today().isoformat())

    @app.route("/orders/<int:order_id>")
    @login_required
    def order_detail(order_id: int):
        order = repository.get_order(order_id)
        if not order:
            flash("Order not found.", "danger")
            return redirect(url_for("orders"))
        return render_template("orders/form.html", order=order,
                               items=repository.list_order_items(order_id),
                               products=[])

    @app.route("/orders/<int:order_id>/ship", methods=["POST"])
    @login_required
    def order_ship(order_id: int):
        order = repository.get_order(order_id)
        if not order:
            flash("Order not found.", "danger")
            return redirect(url_for("orders"))
        if order["status"] == "shipped":
            flash(translations.tr("info.already_shipped_title"), "info")
            return redirect(url_for("orders"))

        # Check stock availability per item. Warn (don't block) if any item
        # would go negative — the user already confirmed shipment.
        items = repository.list_order_items(order_id)
        shortages = []
        for it in items:
            available = repository.product_stock_total(it["product_id"])
            if it["quantity"] > available:
                shortages.append(
                    f"{it['product_code']} {it['color']}/{it['size']}: "
                    f"need {it['quantity']}, have {available}"
                )
        if shortages:
            flash(
                translations.tr("confirm.ship_shortage_msg") + " "
                + "; ".join(shortages),
                "warning",
            )
        try:
            repository.ship_order(order_id)
            flash(translations.tr("status.shipped"), "success")
        except Exception as exc:
            flash(f"Cannot ship: {exc}", "danger")
        return redirect(url_for("orders"))

    @app.route("/orders/<int:order_id>/unship", methods=["POST"])
    @login_required
    def order_unship(order_id: int):
        try:
            repository.unship_order(order_id)
            flash(translations.tr("status.new"), "success")
        except Exception as exc:
            flash(f"Cannot revert: {exc}", "danger")
        return redirect(url_for("orders"))

    @app.route("/orders/<int:order_id>/delete", methods=["POST"])
    @login_required
    def order_delete(order_id: int):
        try:
            repository.delete_order(order_id)
            flash("Order deleted.", "success")
        except Exception as exc:
            flash(f"Cannot delete: {exc}", "danger")
        return redirect(url_for("orders"))

    # ---- Statistics ----------------------------------------------------
    @app.route("/stats")
    @login_required
    def stats():
        from datetime import date as _date
        today = _date.today()
        start_str = request.args.get("from") or today.replace(day=1).isoformat()
        end_str = request.args.get("to") or today.isoformat()
        product_id = request.args.get("product_id") or None
        if product_id:
            product_id = int(product_id)
        summary = repository.sales_summary(start_str, end_str, product_id=product_id)
        return render_template(
            "stats.html",
            summary=summary,
            top=summary["top_products"],
            products=repository.list_products(),
            start=start_str, end=end_str,
            product_id=product_id,
        )

    @app.route("/api/timeseries")
    @login_required
    def api_timeseries():
        start = request.args.get("from")
        end = request.args.get("to")
        metric = request.args.get("metric", "revenue")
        product_id = request.args.get("product_id") or None
        if product_id:
            product_id = int(product_id)
        if not start or not end:
            return jsonify({"labels": [], "values": []})
        # Pick bucket size from the span.
        from datetime import date as _date
        span = (_date.fromisoformat(end) - _date.fromisoformat(start)).days
        bucket = "day" if span <= 21 else ("week" if span <= 120 else "month")
        series = repository.sales_timeseries(start, end, bucket=bucket, product_id=product_id)
        labels = [s["bucket"] for s in series]
        values = [float(s[metric]) for s in series]
        return jsonify({"labels": labels, "values": values, "metric": metric})

    # ---- Profile: change own password ----------------------------------
    @app.route("/profile", methods=["GET", "POST"])
    @login_required
    def profile():
        user = current_user()
        if request.method == "POST":
            old = request.form.get("old_password", "")
            new = request.form.get("new_password", "")
            confirm = request.form.get("confirm_password", "")
            row = get_user_by_username(user.username)
            if not row or not verify_password(row["password_hash"], old):
                flash(translations.tr("err.wrong_password"), "danger")
            elif len(new) < 4:
                flash(translations.tr("err.password_short"), "danger")
            elif new != confirm:
                flash(translations.tr("err.password_mismatch"), "danger")
            else:
                change_password(user.id, new)
                flash(translations.tr("info.password_changed"), "success")
                return redirect(url_for("inventory"))
        return render_template("profile.html")

    # ---- Admin: manage users -------------------------------------------
    @app.route("/admin/users", methods=["GET", "POST"])
    @admin_required
    def admin_users():
        if request.method == "POST":
            action = request.form.get("action", "create")
            if action == "create":
                username = request.form.get("username", "").strip()
                password = request.form.get("password", "")
                display = request.form.get("display_name", "").strip()
                make_admin = request.form.get("is_admin") == "1"
                if not username or len(password) < 4:
                    flash(translations.tr("err.invalid_input"), "danger")
                else:
                    try:
                        create_user(username, password, display, make_admin)
                        flash(translations.tr("info.user_created", username=username), "success")
                    except Exception:
                        flash(translations.tr("err.user_exists"), "danger")
            elif action == "delete":
                uid = int(request.form.get("user_id", "0"))
                me = current_user()
                if uid == me.id:
                    flash(translations.tr("err.cannot_delete_self"), "danger")
                else:
                    delete_user(uid)
                    flash(translations.tr("info.user_deleted"), "success")
            elif action == "reset_password":
                uid = int(request.form.get("user_id", "0"))
                new_pass = request.form.get("new_password", "")
                if len(new_pass) < 4:
                    flash(translations.tr("err.password_short"), "danger")
                else:
                    change_password(uid, new_pass)
                    flash(translations.tr("info.password_changed"), "success")
            return redirect(url_for("admin_users"))
        return render_template("admin_users.html", users=list_users())

    # ---- Admin: wipe all business data ----------------------------------
    @app.route("/admin/reset-db", methods=["POST"])
    @admin_required
    def admin_reset_db():
        """Delete ALL products, orders and stock movements. Users are kept."""
        if request.form.get("confirm") != "RESET":
            flash(translations.tr("err.confirm_reset"), "danger")
            return redirect(url_for("admin_users"))
        with db.transaction() as cur:
            cur.execute(
                "TRUNCATE order_items, stock_out, stock_in, "
                "product_variants, orders, products RESTART IDENTITY CASCADE"
            )
        _thumb_cache.clear()
        flash(translations.tr("info.db_reset"), "success")
        return redirect(url_for("inventory"))

    # ---- Admin: download full backup as one JSON file --------------------
    @app.route("/admin/backup")
    @admin_required
    def admin_backup():
        """Export the entire database as a single downloadable JSON file.

        Every table (including user password hashes and product images as
        base64) is included, so the file is a complete, restorable snapshot.
        """
        import base64
        import json as _json
        from decimal import Decimal
        from datetime import date as _date, datetime as _dt

        def _jsonable(value):
            if isinstance(value, (bytes, memoryview)):
                return base64.b64encode(bytes(value)).decode("ascii")
            if isinstance(value, Decimal):
                return float(value)
            if isinstance(value, (_dt, _date)):
                return value.isoformat()
            return value

        def table(name, order_by="id"):
            rows = db.query(f"SELECT * FROM {name} ORDER BY {order_by}")
            return [{k: _jsonable(v) for k, v in row.items()} for row in rows]

        payload = {
            "meta": {
                "app": "stock",
                "format": 1,
                "created": _dt.now().isoformat(timespec="seconds"),
                "tables": ["users", "products", "product_variants",
                           "stock_in", "stock_out", "orders", "order_items"],
                "note": "Product images are base64-encoded JPEG bytes.",
            },
            "users": table("users"),
            "products": table("products"),
            "product_variants": table("product_variants"),
            "stock_in": table("stock_in"),
            "stock_out": table("stock_out"),
            "orders": table("orders"),
            "order_items": table("order_items"),
        }
        body = _json.dumps(payload, ensure_ascii=False, indent=1)
        filename = f"stock-backup-{date.today().isoformat()}.json"
        return Response(
            body,
            mimetype="application/json",
            headers={
                "Content-Disposition": f"attachment; filename={filename}",
            },
        )

    # ---- CLI commands --------------------------------------------------
    @app.cli.command("init-db")
    def init_db_cmd():
        """Create all database tables (idempotent)."""
        db.init_schema()
        click.echo("Database schema created/verified.")

    @app.cli.command("create-user")
    @click.argument("username")
    @click.argument("password")
    @click.option("--display", default="", help="Display name shown in the UI.")
    def create_user_cmd(username: str, password: str, display: str):
        """Create a login account."""
        uid = create_user(username, password, display)
        click.echo(f"Created user '{username}' (id={uid}).")

    @app.cli.command("recompress-images")
    def recompress_images_cmd():
        """Re-compress every stored product image to the current size/quality.

        Run this once after deploying newer image-optimisation settings, or to
        shrink photos that were uploaded before compression was added.
        """
        rows = db.query("SELECT id FROM products WHERE image IS NOT NULL ORDER BY id")
        if not rows:
            click.echo("No product images to recompress.")
            return
        total_before = 0
        total_after = 0
        count = 0
        for r in rows:
            pid = r["id"]
            raw = db.query_one("SELECT image FROM products WHERE id = %s", (pid,))["image"]
            if not raw:
                continue
            before = len(raw)
            new_bytes, _ = _optimise_image(raw)
            after = len(new_bytes)
            db.execute(
                "UPDATE products SET image = %s, image_ext = '.jpg' WHERE id = %s",
                (new_bytes, pid),
            )
            _thumb_cache.pop(pid, None)
            total_before += before
            total_after += after
            count += 1
            click.echo(f"  product #{pid}: {before:,} -> {after:,} bytes")
        if count:
            ratio = total_before / max(1, total_after)
            click.echo(
                f"\nRecompressed {count} image(s): "
                f"{total_before:,} -> {total_after:,} bytes ({ratio:.1f}x smaller)."
            )

    return app


# 1x1 transparent PNG used as a placeholder when a product has no image.
_PLACEHOLDER_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4"
    "890000000d49444154789c63000100000005000100" + "0d0a2db4" + "0000000049454e44ae426082"
)


app = create_app()


if __name__ == "__main__":
    app.run(debug=True, port=5000)
